# Generated by Django 3.2.15 on 2022-09-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20220905_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date',), 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
