# Generated by Django 3.2.14 on 2022-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_customer_reservation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfFood', models.CharField(max_length=30)),
                ('meat', models.CharField(max_length=30)),
                ('allergy', models.CharField(max_length=30)),
                ('food_details', models.CharField(max_length=150)),
            ],
        ),
    ]
