# Generated by Django 3.2.14 on 2022-07-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
