# Generated by Django 3.2.14 on 2022-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_remove_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='Kings Place', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Kristiansund', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='Norway', max_length=120),
        ),
    ]
