# Generated by Django 3.2.15 on 2022-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_auto_20220726_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='EnterEmail@Email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_person',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(default=12345678),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
