# Generated by Django 3.2.15 on 2022-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20220817_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='spot',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
