# Generated by Django 3.2.15 on 2022-08-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_auto_20220817_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_person',
            new_name='number_of_guests',
        ),
    ]
