# Generated by Django 3.2.15 on 2022-08-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_rename_date_reservation_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='spot',
            new_name='date',
        ),
    ]
