# Generated by Django 3.2.15 on 2022-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_pictures',
            field=models.ImageField(default='/static/img/chicken_tandori_default.jpg', upload_to='files/food'),
        ),
    ]
