# Generated by Django 3.2.15 on 2022-08-22 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_menu_food_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_pictures',
        ),
        migrations.AddField(
            model_name='menu',
            name='food_pic',
            field=cloudinary.models.CloudinaryField(default='/static/img/chicken_tandori_default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
