# Generated by Django 3.2.15 on 2022-08-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_auto_20220822_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='food_pic',
            new_name='image',
        ),
    ]
