# Generated by Django 3.2.15 on 2022-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0018_rename_food_pic_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_details',
        ),
        migrations.AddField(
            model_name='menu',
            name='details',
            field=models.CharField(default='delicious', max_length=160),
        ),
    ]
