# Generated by Django 3.2.15 on 2022-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0019_auto_20220822_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='details',
            field=models.CharField(default='', max_length=160),
        ),
    ]
