# Generated by Django 3.2.15 on 2022-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0020_alter_menu_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='details',
            field=models.CharField(default='', max_length=999),
        ),
    ]
