# Generated by Django 3.2.15 on 2022-08-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0022_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bar.table'),
        ),
    ]
