# Generated by Django 3.2.15 on 2022-08-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0023_reservation_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table',
            new_name='seats',
        ),
    ]
