# Generated by Django 3.2.15 on 2022-08-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0024_rename_table_reservation_seats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time', 'seats')},
        ),
    ]
