# Generated by Django 3.2.15 on 2022-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0037_auto_20220826_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'timeslot', 'seats')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
