# Generated by Django 3.2.15 on 2022-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0038_auto_20220831_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '10:00 – 11:00'), (1, '11:00 – 12:00'), (2, '12:00 – 13:00'), (3, '13:00 – 14:00'), (4, '14:00 – 15:00'), (5, '15:00 – 16:00'), (6, '16:00 – 17:00'), (7, '17:00 – 18:00'), (8, '18:00 – 19:00'), (9, '19:00 – 20:00'), (10, '20:00 – 21:00'), (11, '21:00 – 22:00')], default=0),
        ),
    ]
