# Generated by Django 3.2.15 on 2022-08-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0039_alter_reservation_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='timeslot',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time', 'seats')},
        ),
    ]
