# Generated by Django 3.2.15 on 2022-09-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0042_reservation_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='username',
            new_name='user',
        ),
    ]
